name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0

    - name: Setup Account module
      run: |
        cd J3space.Abp.Account
        dotnet restore
        dotnet build -c Release
        
    - name: Setup IdentityServer module
      run: |
        cd J3space.Abp.IdentityServer
        dotnet restore
        dotnet build -c Release
        
    - name: Setup Sample App
      run: |
        cd J3space.SampleApp
        pwd
        ls
        dir
        dotnet restore
        dotnet build -c Release
        
